name: 'Generate Coverage Report'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Coverage on Ubuntu
    steps:
      - name: Set up JDK and Maven
        uses: s4u/setup-maven-action@ba34de01b7f4ba2ab8e2860df8993a29f4477056 # v1.20.0
        with:
          java-distribution: 'temurin'
          java-version: '21'
      - name: Generate coverage with JaCoCo
        run: mvn clean jacoco:prepare-agent test jacoco:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./target/site/jacoco/jacoco.xml
