# Automates creation of Release Drafts using Release Drafter
# More Info: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
name: Release Drafter

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        with:
          # Publishes a new GH Release automatically once a tag gets pushed
          publish: startsWith(github.ref, "refs/tags")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
